//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRacunalniServis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRacunalniServis.Poruke", typeof(Poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format!.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite email!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unije istu lozinku u potvrdi!.
        /// </summary>
        internal static string err_pass_ns {
            get {
                return ResourceManager.GetString("err_pass_ns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni podaci!.
        /// </summary>
        internal static string log_err {
            get {
                return ResourceManager.GetString("log_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate privilegije!.
        /// </summary>
        internal static string log_err_p {
            get {
                return ResourceManager.GetString("log_err_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li se želite odjaviti?.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je zauzet!.
        /// </summary>
        internal static string mail_con {
            get {
                return ResourceManager.GetString("mail_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime!.
        /// </summary>
        internal static string name_req {
            get {
                return ResourceManager.GetString("name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da bude minimalno 4 karektera!.
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite prekinuti program?.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne možete deaktivirati korisnika koji upravo koristi sistem!.
        /// </summary>
        internal static string status_err {
            get {
                return ResourceManager.GetString("status_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali korisnika!.
        /// </summary>
        internal static string usr_succ {
            get {
                return ResourceManager.GetString("usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjene uspješno spremljene!.
        /// </summary>
        internal static string usr_succ_upd {
            get {
                return ResourceManager.GetString("usr_succ_upd", resourceCulture);
            }
        }
    }
}
